stages:
    - check
    - website

default:
  tags: [docker]

image: rocker/tidyverse:4.0.5

variables:
  R_LIBS_USER: "$CI_PROJECT_DIR/ci/lib"
  CHECK_DIR: "$CI_PROJECT_DIR/ci/logs"
  BUILD_LOGS_DIR: "$CI_PROJECT_DIR/ci/logs/$CI_PROJECT_NAME.Rcheck"

cache:
  paths:
    - $R_LIBS_USER

before_script:
  - mkdir -p $R_LIBS_USER $BUILD_LOGS_DIR
  - echo "R_LIBS='$R_LIBS_USER'" > .Renviron
  - R -e 'devtools::install_deps(dep = T)'

check:
  stage: check
  script:
    - if [[ $NOT_CRAN == "false" ]]; then sudo apt-get update && sudo apt-get install -y qpdf; fi
    - R -e 'rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "warning")'

website:
  stage: website
  only:
    - master
    - dev
    - tags
  script:
    - R -e 'devtools::update_packages(packages = "pkgdown")'
    - R -e 'pkgdown::build_site()'
    - sudo apt-get update && sudo apt-get install -y sshpass rsync
    - sshpass -p "${OVH_PASS}" rsync -a -e "ssh -o StrictHostKeyChecking=no" docs/ ${OVH_LOGIN}@${OVH_SFTP}:/home/${OVH_LOGIN}/in-wop/hubeau/
