default:
  api_url: https://hubeau.eaufrance.fr/api
  apis:
    prelevements:
      path: v1/prelevements
      operations:
        points_prelevement:
          path: referentiel/points_prelevement
          fields:
           - code_bdlisa
           - code_bss_point_eau
           - code_commune_insee
           - code_departement
           - code_entite_hydro_cours_eau
           - code_entite_hydro_plan_eau
           - code_mer_ocean
           - code_nature
           - code_ouvrage
           - code_point_prelevement
           - code_type_milieu
           - code_zone_hydro
           - date_exploitation
           - fields
           - libelle_departement
           - nappe_accompagnement
           - nom_commune
           - nom_point_prelevement
        chroniques:
          path: chroniques
          fields:
            - annee
            - bbox
            - code_commune_insee
            - code_departement
            - code_mode_obtention_volume
            - code_ouvrage
            - code_qualification_volume
            - code_statut_instruction
            - code_statut_volume
            - code_usage
            - distance
            - fields
            - latitude
            - libelle_departement
            - longitude
            - nom_commune
            - prelevement_ecrasant
            - producteur_donnee
            - volume_max
            - volume_min
        ouvrages:
          path: referentiel/ouvrages
          fields:
            - bbox
            - code_bdlisa
            - code_commune_insee
            - code_departement
            - code_entite_hydro_cours_eau
            - code_entite_hydro_plan_eau
            - code_mer_ocean
            - code_ouvrage
            - code_type_milieu
            - codes_points_prelevements
            - date_exploitation
            - distance
            - fields
            - latitude
            - libelle_departement
            - longitude
            - nom_commune
            - nom_ouvrage
    indicateurs_services:
      path: v0/indicateurs_services
      operations:
        communes:
          path: communes
          fields:
            - annee
            - code_commune
            - code_departement
            - detail_service
            - fields
            - type_service
        indicateurs:
          path: indicateurs
          fields:
            - annee
            - code_indicateur
            - fields
        services:
          path: services
          fields:
            - annee
            - code_commune
            - code_departement
            - fields
            - type_service
    hydrometrie:
      path: v1/hydrometrie
      operations:
        stations:
          path: referentiel/stations
          fields:
            - bbox
            - code_commune_station
            - code_cours_eau
            - code_departement
            - code_region
            - code_sandre_reseau_station
            - code_site
            - code_station
            - date_fermeture_station
            - date_ouverture_station
            - distance
            - en_service
            - fields
            - latitude
            - libelle_cours_eau
            - libelle_site
            - libelle_station
            - longitude
        sites:
          path: referentiel/sites
          fields:
            - bbox
            - code_commune_site
            - code_cours_eau
            - code_departement
            - code_region
            - code_site
            - code_troncon_hydro_site
            - code_zone_hydro_site
            - distance
            - fields
            - latitude
            - libelle_cours_eau
            - libelle_site
            - longitude
        observations_tr:
          path: observations_tr
          fields:
            - bbox
            - code_entite
            - cursor
            - date_debut_obs
            - date_fin_obs
            - distance
            - fields
            - grandeur_hydro
            - latitude
            - longitude
            - timestep
