default:
  url: https://bnpe.eaufrance.fr/Bnpe-Diffusion/synthese
  url_time_series: synthese_temporelle
  url_com_series: synthese_geographique
  user_agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0
